# Is the plugin enabled?
enabled: true

# The locale of the message file
# Currently: en, cs, de, es, fr, ja, ko, nl, pl, pt-br, ru, tr, vn, zh_cn
# Delete messages.yml before changing this
locale: en

# The decimal format of the plugin
# Used to change default formatting for numbers, for example: en_US for 1,000.99 or de_DE for 1.000,99
# Note: all locales supported by the jvm are avaialable.
# Only relevant if you use vault
decimal-locale: en_US

# Should EMF fish only be given during a competition?
fish-only-in-competition: false

# Should competition player requirements respect vanished players?
# Supports EssentialsX and CMI.
respect-vanished: true

# WARNING EXPERIMENTAL: This feature is experimental and may not work properly.
# The plugin stores stats about fish caught by players, used in the fish log. Disabling this will disable functionality
# of this feature.
# ATTENTION: Toggling this requires a full server restart.
database:
  enabled: false
  # Available option are: mysql, sqlite
  type: sqlite
  # The address of the database
  # (the port 3306 is automatically added in by default, if different: specify with address:port)
  address: localhost
  # The name of the database to store fish data in
  database: evenmorefish
  # The table prefix for the database.
  # WARNING: Changing this will create new tables in the database.
  # Only use this during first setup or before migrations.
  # (Or after, but only if you know what you're doing).
  table-prefix: "emf_"
  # Login information
  username: root
  password: ''

# Prevents verbose output when the plugin interacts with the database.
disable-db-verbose: true


# When dropping tool items (e.g. fishing rod) should they be dropped with a random durability
# instead of always full durability?
random-durability: true

# Setting this to false disables /emf shop and money rewards from competitions. It's unlikely
# you'll want to do this, but it is possible.
enable-economy: true

# Choose which economy plugin you wish to use
# Supported values are: Vault, PlayerPoints, GriefPrevention, None
economy-type: Vault

# Setting this to change the boosbar style
# you can use like: SEGMENTED_6 SEGMENTED_10 SEGMENTED_12 SEGMENTED_20 SOLID
barstyle: 'SEGMENTED_10'

# Requires that the fishing rod to have the "emf-rod-nbt" value in order to catch custom fish defined in fish.yml.
# This allows you to sell rods that will be the only ones able to catch EvenMoreFish fish.
require-nbt-rod: false

# This defines the item given with the "/emf admin rod-nbt -p:Playername" command. It uses the same formatting as the fish
# and baits in fish & baits .yml files.
nbt-rod-item:
  item:
    # This needs to be FISHING_ROD
    material: FISHING_ROD
    displayname: "&eEvenMoreFish Fishing Rod"
  glowing: true
  lore:
    - ""
    - "&7Catch &ecustom &7fish using this"
    - "&7fishing rod."

# Should the user need emf.use_rod permission in order to catch default custom fish defined in fish.yml. This requires
# Vault and a permission manager such as LuckPerms.
requires-fishing-permission: false

# Should fish and baits be blocked from being crafted into other items. For example, when the player tries to craft
# the starfish into a beacon.
block-crafting: true

# /emf shop configuration. If you wish to change the layout, please look at the guis.yml file.
sell-gui:
  # Should the items be dropped(false) or sold(true) when a player exits an inventory?
  sell-over-drop: false

# Uncomment the below section to enable these feature. They sett the plugin to only give custom fish when users are
# in a list of set defined regions (this requires the worldguard/redprotect plugin) and/or in a list of set defined
# worlds. EvenMoreFish automatically detects your protection plugin so it's important you don't run both at once.
# Note- Changing this value requires a SERVER RESTART NOT A RELOAD.
allowed-regions:
  - "fishing"

allowed-worlds:
  - "world"

# This section defines the boost settings for different regions.
# Each rarity of fish has a boost multiplier that adjusts its weight in the specified region.
# To disable a boost, comment out the corresponding line.
# Region boost settings
#region-boosts:
  #fishing:
    # The boost multiplier for the "Common" rarity in the "fishing" region.
    # This means the weight of "Common" fish will be multiplied by 0.5.
    # To disable, comment out the line below.
    #common: 0.5

    # The boost multiplier for the "Rare" rarity in the "fishing" region.
    # This means the weight of "Rare" fish will be multiplied by 1.0 (no change).
    # To disable, comment out the line below.
    #rare: 1.0

    # The boost multiplier for the "Epic" rarity in the "fishing" region.
    # This means the weight of "Epic" fish will be multiplied by 3.0.
    # To disable, comment out the line below.
    #epic: 3.0

    # The boost multiplier for the "Legendary" rarity in the "fishing" region.
    # This means the weight of "Legendary" fish will be multiplied by 15.0.
    # To disable, comment out the line below.
    #legendary: 15.0

# Prevents mcMMO from overriding fishing loot, this means treasure won't appear when fish can.
disable-mcmmo-loot: true

# Prevents AureliumSkills from overriding fishing loot, this means treasure won't appear when fish can.
disable-aureliumskills-loot: true

# When set to true, players won't be able to place fish that are heads, like head-64 or head-uuid.
place-head-fish: false

# Switch between custom fish or vanilla fishing
vanilla-fishing: true

# Whether to protect baited fishing rods in an anvil.
protect-baited-rods: true


# Requirement configs
requirements:
  nearby-players:
    # How far should the plugin check in blocks? Large values may cause lag.
    range: 20

# When the player catches a fish, should the fish be put straight into the inventory instead of the vanilla catching animation.
give-straight-to-inventory: false

# Customize the plugin's command. Requires a server restart to take effect.
command:
  # The plugin's main command
  main: "emf"
  # Aliases for the main command
  aliases:
    - "evenmorefish"

# Customizable sets of biomes for fish.yml configuration
biome-sets:
  # oceans biome set. you can add more sets as you please.
  oceans:
    - COLD_OCEAN
    - DEEP_COLD_OCEAN
    - DEEP_LUKEWARM_OCEAN
    - DEEP_OCEAN
    - LUKEWARM_OCEAN
    - OCEAN
    - WARM_OCEAN

# ATTENTION ATTENTION ATTENTION
# DO NOT EDIT THIS VALUE OR THINGS WILL BREAK!!!
config-version: 4
