# Is the plugin enabled?
enabled: true

# Should EMF fish only be given during a competition?
fish-only-in-competition: false

# Should a database store data about fish such as how many have been caught and the first to catch it.
# Setting to false will disable it. In a future update this will have a deeper meaning and purpose.
database: true

# When dropping tool items (e.g. fishing rod) should they be dropped with a random durability
# instead of always full durability?
random-durability: true


competitions:

  # When should competitions run?
  # It will use server's local timezone using a 24hour time format
  times:
    - "00:00" # midnight
    - "06:00"
    - "12:00" # midday
    - "18:00"

  # How long should the competition go on for? (In minutes)
  duration: 10

  # What colour should the bossbar cooldown be? (values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html)
  # Set the text and text colour above the bossbar in messages.yml
  bossbar-colour: GREEN

  winnings:
    1:
      # Commands are run by the console, it's advised to change these before releasing your server.
      - "COMMAND:give {player} diamond 5"
      - "MESSAGE:&aCongratulations for coming 1st!"
      # Can't contain decimals.
      - "MONEY:5000"
      # formatted as "effect_name,amplifier,duration"
      - "EFFECT:SPEED,2,5"
      - "ITEM:DIAMOND,2"
    2:
      - "ITEM:DIAMOND,1"
      - "MESSAGE:&bCongratulations for coming 2nd!"
      - "MONEY:2500"
    3:
      - "EFFECT:SPEED,1,5"
      - "MESSAGE:&eCongratulations for coming 3rd!"
      - "MONEY:1000"
  # Add as many more places as you need

  # This is the minimum needed amount of players for an automatic competition to start.
  minimum-players: 5

# Should broadcasted catches (defined in rarities.yml) only be shown to players holding fishing rods?
broadcast-only-rods: true

# Uncomment the below section to enable this feature. It sets the plugin to only give custom fish when users are
# in a list of set defined regions (this requires the worldguard plugin).
#allowed-regions:
#  - "fishing"


# ATTENTION ATTENTION ATTENTION
# DO NOT EDIT THIS VALUE UNLESS YOU'RE UPDATING THE CONFIG.
config-version: 3