# Is the plugin enabled?
enabled: true

# Should EMF fish only be given during a competition?
fish-only-in-competition: false

# The plugin stores stats about fish caught by players, used in the fish log. Disabling this will disable functionality
# of this feature.
database: true
# Info for connecting to a mysql database:
mysql:
  # Set to false if you're using a standard SQLITE .db file
  use-mysql: false
  # The address of the database (the port 3306 is automatically added in by default, if different: specify with address:port)
  address: localhost
  # The name of the database to store fish data in
  database: evenmorefish
  # Login information
  username: root
  password: ''

# When dropping tool items (e.g. fishing rod) should they be dropped with a random durability
# instead of always full durability?
random-durability: true

# Should the plugin hook into vault economy? Having this disabled will only disable /emf shop.
enable-economy: true

# For customizing the /emf shop GUI
gui:
  # Fills the empty slots of a normal /emf shop
  filler: GRAY_STAINED_GLASS_PANE
  # Fills the empty slots of /emf shop when there's an error (i.e. the player trying to sell nothing)
  filler-error: RED_STAINED_GLASS_PANE
  # The item for the player to click to sell their fish
  sell-item: GOLD_INGOT
  # The slot to put the item in on the bottom row, accepts values 1-9 inclusive.
  sell-slot: 4
  # The item for the player to click to automatically sell all their fish
  sell-all-item: COD_BUCKET
  # The slot to put the item in on the bottom row, accepts values 1-9 inclusive.
  sell-all-slot: 6
  # The item for the player to click to confirm selling their fish
  sell-item-confirm: GOLD_BLOCK
  # The item for the player to click to confirm selling all of their fish
  sell-all-item-confirm: TROPICAL_FISH_BUCKET
  # The item shown to the player when an error occurs (trying to sell nothing of value from the gui)
  sell-item-error: REDSTONE_BLOCK
  # The item shown to the player when an error occurs (trying to sell nothing of value from their inventory)
  sell-all-item-error: SALMON_BUCKET
  # How many rows the selling area of the GUI should be (max 5, min 1)
  size: 3
  # Should the items be dropped(false) or sold(true) when a player exits an inventory?
  sell-over-drop: false

# Uncomment the below section to enable these feature. They sett the plugin to only give custom fish when users are
# in a list of set defined regions (this requires the worldguard/redprotect plugin) and/or in a list of set defined
# worlds. EvenMoreFish automatically detects your protection plugin so it's important you don't run both at once.
# Note- Changing this value requires a SERVER RESTART NOT A RELOAD.
#allowed-regions:
#  - "fishing"
#
#allowed-worlds:
#  - "fishworld"

# Prevents mcMMO from overriding fishing loot, this means treasure won't appear when fish can.
disable-mcmmo-loot: true

# ATTENTION ATTENTION ATTENTION
# DO NOT EDIT THIS VALUE UNLESS YOU'RE UPDATING THE CONFIG.
config-version: 8