# Is the plugin enabled?
enabled: true

# Should EMF fish only be given during a competition?
fish-only-in-competition: false

# Should a database store data about fish such as how many have been caught and the first to catch it.
# Setting to false will disable it.
database: true


competitions:

  # When should competitions run?
  # It will use server's local timezone using a 24hour time format
  times:
    - "00:00" # midnight
    - "06:00"
    - "12:00" # midday
    - "18:00"

  # How long should the competition go on for? (In minutes)
  duration: 10

  winnings:
    1:
      # Commands are run by the console, it's advised to change these before releasing your server.
      - "COMMAND:give {player} diamond 5"
      - "MESSAGE:&aCongratulations!"
      # Can't contain decimals.
      - "MONEY:5000"
      # formatted as "effect_name,amplifier,duration"
      - "EFFECT:SPEED,1,5"
      - "ITEM:DIAMOND,1"
    2:
      - "ITEM:DIAMOND,1"
      - "MESSAGE:&bCongratulations!"
      - "MONEY:2500"
    3:
      # EFFECT NAME, EFFECT STRENGTH, LENGTH(SECONDS)
      - "EFFECT:SPEED,2,5"
      - "MESSAGE:&eCongratulations!"
      - "MONEY:1000"
